name: ampdocker
services:
  amp-docker:
    image: kerklangsi/amp-docker:latest
    container_name: amp-docker
    environment:
      - TZ=UTC
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 7777
        published: "7777"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /home/amp/.local/share/CubeCoders/AMP

x-casaos:
  architectures:
    - amd64
  author: kerklangsi
  category: Others
  description:
    en_US: CubeCoders AMP (Application Management Panel) allows you to easily create, host, manage, and monitor dedicated game servers for various titles directly on ZimaOS.
  developer: CubeCoders / kerklangsi
  icon: https://cdn.jsdelivr.net/gh/kerklangsi/zimaos-appstore@gh-pages/apps/ampdocker/assets/icon.svg
  id: ampdocker
  index: /
  main: amp-docker
  port_map: "8080"
  scheme: http
  tagline:
    en_US: CubeCoders AMP in a Docker container for game server management
  title:
    en_US: AMP Game Server
  version: 1.0.0
  volumes:
    - container: /var/run/docker.sock
      description:
        en_US: Docker Socket
    - container: /home/amp/.local/share/CubeCoders/AMP
      description:
        en_US: AMP Data Directory
