name: amp-docker
services:
  amp-docker:
    image: kerklangsi/amp-docker:latest
    container_name: amp-docker
    network_mode: bridge
    environment:
    - TZ=UTC
    ports:
    - target: 8080
      published: '8080'
      protocol: tcp
    - target: 7777
      published: '7777'
      protocol: udp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/docker.sock
      target: /var/run/docker.sock
x-casaos:
  architectures:
  - amd64
  author: kerklangsi
  category: Media
  min_memory: 512MB
  min_disk: 2000MB
  description:
    en_US: 'CubeCoders AMP in a Docker Image. Easily create game servers for games


      ### Features

      - Simple, one-click deployment for ZimaOS and CasaOS.

      - Persistent data volume storage.

      - High-performance containerized execution.'
  developer: kerklangsi
  icon: https://kerklangsi.github.io/zimaos-appstore/apps/amp-docker/assets/icon.svg
  thumbnail: https://kerklangsi.github.io/zimaos-appstore/apps/com.kerklangsi.amp-docker/assets/icon.svg
  id: com.kerklangsi.amp-docker
  index: /
  main: amp-docker
  port_map: '80'
  scheme: http
  tagline:
    en_US: CubeCoders AMP in a Docker Image
  title:
    en_US: Amp Docker
  version: latest
  release_notes:
    en_US: '### What''s New in v1.0.0

      - Initial release of CubeCoders AMP container for ZimaOS App Store.

      - Preconfigured Docker socket binding and persistent storage for server data.

      '
  tips:
    en_US: Ensure port 80 is not in use before installing.
  volumes:
  - container: /var/run/docker.sock
    description:
      en_US: Persistent storage for /var/run/docker.sock
