name: com.kerklangsi.ampdocker
services:
  amp-docker:
    image: kerklangsi/amp-docker:latest
    container_name: amp-docker
    environment:
      - TZ=UTC
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 7777
        published: "7777"
        protocol: udp
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /home/amp/.local/share/CubeCoders/AMP

x-casaos:
  icon: https://cdn.jsdelivr.net/gh/kerklangsi/zimaos-appstore@gh-pages/apps/com.kerklangsi.ampdocker/assets/icon.svg
  id: com.kerklangsi.ampdocker
  index: /
  main: amp-docker
  port_map: "8080"
  scheme: http
  title:
    en_US: AMP Game Server
  version: 1.0.0
