name: github-runner
services:
  github-runner:
    image: kerklangsi/github-runner-docker:latest
    container_name: github-runner-docker
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
    environment:
      - REPO_URL=https://github.com/kerklangsi/your-repo
      - ACCESS_TOKEN=
      - RUNNER_TOKEN=
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: /DATA/AppData/github-runner/runner
        target: /opt/github-runners
      - type: bind
        source: /DATA/AppData/github-runner/data
        target: /app/data

x-casaos:
  architectures:
    - amd64
  author: kerklangsi
  category: Developer
  description:
    en_US: Manage multiple self-hosted GitHub Actions runners inside a single container with live logs, resource monitoring, and web UI.
  developer: kerklangsi
  icon: https://cdn.jsdelivr.net/gh/kerklangsi/zimaos-appstore@gh-pages/apps/github-runner/assets/icon.svg
  id: github-runner
  store_app_id: githubrunner
  index: /
  main: github-runner
  port_map: "3000"
  scheme: http
  tagline:
    en_US: Multi-runner GitHub Actions manager with Web Dashboard for ZimaOS
  title:
    en_US: GitHub Runner Manager
  version: 2.0.0
  volumes:
    - container: /opt/github-runners
      description:
        en_US: GitHub Runners Storage
    - container: /app/data
      description:
        en_US: Application Data



