name: mysql
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    network_mode: bridge
x-casaos:
  title:
    en_US: Mysql
  tagline:
    en_US: MySQL is a widely used, open-source relational database management system
      (RDBMS).
  description:
    en_US: 'MySQL is a widely used, open-source relational database management system
      (RDBMS).


      ### Features

      - Simple, one-click deployment for ZimaOS and CasaOS.

      - Persistent data volume storage.

      - High-performance containerized execution.'
  category: Developer Tools
  developer: library
  author: library
  port_map: '80'
  scheme: http
  index: /
  tips:
    before_install:
      en_US: Ensure port 80 is not in use before installing.
    after_install:
      en_US: Open the Web Dashboard at http://<your-zimaos-ip>:80
  id: com.library.mysql
  main: mysql
